# Generated by Django 5.0.4 on 2024-04-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis_app', '0002_remove_venue_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
